version: '2.0'
services:
  nginx:
   image: nginx:alpine
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d   

  app:
    restart: always
    build: .
    image: dextra-challenge
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    links:
      - "nginx"